---
- name: install yum packages as prerequisites
  hosts: linux
  remote_user: root
  vars:
    proxy: 172.18.32.94:3128
  tasks:
    - name: install libselinux-python for ansible play (create group)
      yum: name=libselinux-python state=present
      environment:
        http_proxy: '{{ proxy }}'

    - name: install vsftpd on first host of group
      yum: name=vsftpd state=present
      environment:
        http_proxy: '{{ proxy }}'
      when: ansible_host == 'linux-serv01'
...
